server:
  port: 8090

spring:
  application:
    name: ai-service

  datasource:
    url: jdbc:h2:mem:iadb
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: google/gemini-pro
          temperature: 0.7
          max-tokens: 2000

aws:
  s3:
    endpoint: http://localhost:4566

ai:
  documents:
    bucket: document-bucket

app:
  message: IA Service - Configured from Config Server
