server:
  port: 8083

spring:
  application:
    name: claim-service
  datasource:
    url: jdbc:h2:mem:claimdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console

app:
  message: Claim Service - Configured from Config Server