server:
  port: 8085

spring:
  application:
    name: document-service
  datasource:
    url: jdbc:h2:mem:documentdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}


file:
  upload-dir: uploads

app:
  message: Document Service - Configured from Config Server