server:
  port: 8081

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:h2:mem:memberdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console

app:
  message: Member Service - Configured from Config Server