server:
  port: 8084

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  message: Notification Service - Configured from Config Server